### PR TITLE
Prepare 0.2.4.2 release.

### PR DESCRIPTION
**Pull request by brianjosephmckeon**
Reformatted.
Use new .github workflows.
Updated package metadata.

### CODE REVIEW

**Comment by brianjosephmckeon** [comment]
@andrewthad
Having trouble trying to build country's bench-size target on GHC 9.8.1.
The issue stems from its dependence on compact.
I've commented out the build target for now.

**Comment by ysangkok** [comment]
@brianjosephmckeon From [the hackage page](https://hackage.haskell.org/package/compact), it looks like compact should be compatible with ghc 9.8. Which issue are you encountering?

**Comment by andrewthad** [comment]
I've made a few changes, and I pushed a metadata revision for colonnade.

**Comment by ysangkok** [comment]
Thank you! I don't see the 0.2.4.2 of the `country` library on Hackage, but I suppose that is expected?

**Comment by andrewthad** [comment]
Released to hackage just now.

**Pull request merged**
